PITY_EPIC = 10
PITY_LEGENDARY = 40
GUARANTEED_LEGENDARY = 10
RAPTOR1_COUNT_COMMON = 106
RAPTOR1_COUNT_RARE = 78
RAPTOR1_COUNT_EPIC = 54
RAPTOR1_COUNT_LEGENDARY = 27
PACK_DROP_RATE_LEGENDARY = 0.05
CARD_DROP_RATE_LEGENDARY = PACK_DROP_RATE_LEGENDARY / 5
PACK_DROP_RATE_EPIC = 0.21
CARD_DROP_RATE_EPIC = PACK_DROP_RATE_EPIC / 5
PACK_DROP_RATE_RARE = 0.50
CARD_DROP_RATE_RARE = PACK_DROP_RATE_EPIC / 5



